tools:
    external_code_coverage: true

filter:
    paths:
        - src/
    dependency_paths:
        - vendor/

checks:
    php: true

build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.4
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run
