dist: focal
language: php

php:
    - '8.2'

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - pecl channel-update pecl.php.net
    - yes | pecl install pcov
    - phpenv config-rm xdebug.ini
    - composer self-update --2

install:
    - composer validate --ansi --no-interaction --strict
    - composer install --ansi --no-interaction --no-suggest

script:
    - vendor/bin/phpcs -ps
    - vendor/bin/phpstan analyse --ansi --no-progress
    - vendor/bin/psalm --no-progress --threads=8
    - vendor/bin/phpunit --coverage-clover clover.xml

after_success:
    - travis_retry wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.6.0/php-coveralls.phar
    - travis_retry php php-coveralls.phar -e test -x clover.xml -o coveralls.json
