version: '3.4'

services:
    nginx:
        depends_on:
            - php
        container_name: doop-nginx
        image: nginx:1.19-alpine
        restart: on-failure
        volumes:
            - ./:/app:ro
            - ./docker/nginx/micker.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8080:8080

    php:
        build:
            context: docker/php
            target: development
        restart: on-failure
        volumes:
            - ./:/app:rw
        user: ${HOST_UID:-1000}:${HOST_GID:-1001}
        environment:
            XDEBUG_CONFIG: ${XDEBUG_CONFIG:-remote_host=172.19.0.1 remote_port=9009}
