version: '3.4'

services:
    php:
        build:
            context: docker/php
            target: development
        restart: on-failure
        command: php -S 0.0.0.0:8080 -t public
        ports:
            - 8080:8080
        volumes:
            - ./:/app
        user: ${HOST_UID:-1000}:${HOST_GID:-1001}
        environment:
            XDEBUG_CONFIG: ${XDEBUG_CONFIG:-remote_host=172.19.0.1 remote_port=9009}
