version: '3.4'

services:
    nginx:
        depends_on:
            - php
        image: nginx:1.22-alpine
        restart: on-failure
        volumes:
            - ./:/app:ro
            - ./docker/nginx/micker.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8080:8080

    php:
        build:
            context: docker/php
            target: development
        restart: on-failure
        volumes:
            - ./:/app:rw
        environment:
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: >-
                client_host=host.docker.internal
                discover_client_host=true
